#!/bin/bash

cd "$(dirname "$0")"

if [ "$EUID" -eq "0" ]; then
  echo "Don't run this as root"
  exit 1
fi

sudo echo "[ok] sudo works" || exit 1
LOC="$(pwd)"

install_yay() {
  echo "====> Install yay"
  echo "----> 1/2 install requirements"
  sudo pacman -S --needed --noconfirm base-devel git

  echo "----> 2/2 aur yay"
  dir="/tmp/yay"
  sudo rm -rf $dir
  git clone https://aur.archlinux.org/yay.git /tmp/yay
  cd /tmp/yay
  makepkg --noconfirm -si
  cd "$LOC"
}
if command -v yay > /dev/null; then
  echo "[ok] yay is installed"
else
  install_yay
fi

install_node() {
  echo "====> Install node"
  yay -S --noconfirm pnpm
}
if command -v node > /dev/null && \
   command -v npm > /dev/null && \
   command -v yarn > /dev/null; then
  echo "[ok] node is installed"
else
  install_node
fi

yarn
node js/setup.js
