#!/bin/bash

cd "$(dirname "$0")"

if [ "$EUID" -eq "0" ]; then
  echo "Don't run this as root"
  exit 1
fi

sudo echo "[ok] sudo works" || exit 1
LOC="$(pwd)"

install_yaourt() {
  echo "====> Install yaourt"
  echo "----> 1/3 install requirements"
  sudo pacman -S --needed --noconfirm base-devel

  echo "----> 2/3 aur package-query"
  dir="/tmp/package-query"
  sudo rm -rf $dir; mkdir -p $dir && cd $dir
  curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
  tar -xvzf package-query.tar.gz 
  cd package-query
  makepkg --noconfirm -si

  echo "----> 3/3 aur yaourt"
  dir="/tmp/yaourt"
  sudo rm -rf $dir; mkdir -p $dir && cd $dir
  curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
  tar -xvzf yaourt.tar.gz 
  cd yaourt
  makepkg --noconfirm -si
  cd "$LOC"
}
if command -v yaourt > /dev/null; then
  echo "[ok] yaourt is installed"
else
  install_yaourt
fi

install_node() {
  echo "====> Install node"
  yaourt -S --noconfirm nodejs npm yarn
}
if command -v node > /dev/null && \
   command -v npm > /dev/null && \
   command -v yarn > /dev/null; then
  echo "[ok] node is installed"
else
  install_node
fi

yarn
node js/setup.js
