syntax enable
colorscheme monokai

set t_ut=

filetype plugin indent on
set autoindent
set smartindent
set tabstop=2
set shiftwidth=2
set expandtab
" set paste  " deactivated by default, as it conflicts with expandtab

inoremap kj <Esc>
