[preferred]
# Use wlr for screen sharing and screenshots
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
# Use gtk for everything else (file picker, etc.)
default=gtk
